/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author solan
 */
public class Cuidados extends javax.swing.JFrame {

    /**
     * Creates new form Cuidados
     */
    public Cuidados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAccion = new javax.swing.JButton();
        cbxCuidados = new javax.swing.JComboBox<>();
        nombreCuidado = new javax.swing.JLabel();
        Estado = new javax.swing.JButton();
        Tienda = new javax.swing.JButton();
        Cuidados = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAccion.setText("Dar alimento");
        botonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccionActionPerformed(evt);
            }
        });

        cbxCuidados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentar", "Curar", "Pasear", "Limpiar" }));
        cbxCuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCuidadosActionPerformed(evt);
            }
        });

        nombreCuidado.setText("jLabel1");

        Estado.setText("Estado ");
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        Tienda.setText("Tienda");
        Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiendaActionPerformed(evt);
            }
        });

        Cuidados.setBackground(new java.awt.Color(255, 153, 153));
        Cuidados.setText("Cuidados");
        Cuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuidadosActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\solan\\Downloads\\atras (2).png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Tienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(Cuidados, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreCuidado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(cbxCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Cuidados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreCuidado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(botonAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int comidaComprada=0;
    private void botonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccionActionPerformed
       if(cuidadoSeleccionado.equals("Alimentar")){
        if(comidaComprada>0){
            
        }
        
       }else{
         if(cuidadoSeleccionado.equals("Curar")){
            botonAccion.setText("Curar enfermedad");
        } else{
           if(cuidadoSeleccionado.equals("Pasear")){
            botonAccion.setText("Dar un paseo");
        }else{
               if(cuidadoSeleccionado.equals("Limpiar")){
            botonAccion.setText("Limpieza");
        }
           }  
         }
       }
       
    }//GEN-LAST:event_botonAccionActionPerformed

    private void CuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuidadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuidadosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Menu m = new Menu();
        Main pokemon = new Main();
        m.PokemonesVivos(pokemon.Pokemones());
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiendaActionPerformed
        // TODO add your handling code here:
        Llamado una = new Llamado();
        una.llamarTienda();
        this.setVisible(false);
    }//GEN-LAST:event_TiendaActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
          Llamado una = new Llamado();
        una.llamarEstado();
        this.setVisible(false);
    }//GEN-LAST:event_EstadoActionPerformed
    String cuidadoSeleccionado = "";
    private void cbxCuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCuidadosActionPerformed
        // TODO add your handling code here:
       nombreCuidado.setText(cbxCuidados.getSelectedItem().toString());//caso depues***
      cuidadoSeleccionado = cbxCuidados.getSelectedItem().toString();
       if(cuidadoSeleccionado.equals("Alimentar")){
        botonAccion.setText("Dar Alimento");
        
       }else{
         if(cuidadoSeleccionado.equals("Curar")){
            botonAccion.setText("Curar enfermedad");
        } else{
           if(cuidadoSeleccionado.equals("Pasear")){
            botonAccion.setText("Dar un paseo");
        }else{
               if(cuidadoSeleccionado.equals("Limpiar")){
            botonAccion.setText("Limpieza");
        }
           }  
         }
       }
       

    }//GEN-LAST:event_cbxCuidadosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cuidados;
    private javax.swing.JButton Estado;
    private javax.swing.JButton Tienda;
    private javax.swing.JButton botonAccion;
    private javax.swing.JComboBox<String> cbxCuidados;
    private javax.swing.JButton jButton5;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel nombreCuidado;
    // End of variables declaration//GEN-END:variables
}
