
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author solan
 */
public class Estado extends javax.swing.JFrame {

    /**
     * Creates new form Estado
     */
    public Estado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cuidados = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Tienda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Estado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        imagenPokemon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreEstado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Peticion de comida:");

        jLabel4.setText("Peticion de  limpieza:");

        jLabel5.setText("Peticion de paseo:");

        jLabel6.setText("Enfermedades:");

        Cuidados.setText("Cuidados");
        Cuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuidadosActionPerformed(evt);
            }
        });

        jLabel9.setText("x");

        Tienda.setText("Tienda");
        Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiendaActionPerformed(evt);
            }
        });

        jLabel8.setText("x");

        Estado.setBackground(new java.awt.Color(255, 153, 153));
        Estado.setText("Estado ");
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        jLabel7.setText("x");

        jLabel3.setText("x");

        nombreEstado.setText("jLabel1");

        jLabel10.setText("0");

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\solan\\Downloads\\atras (2).png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Tienda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(Cuidados, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(nombreEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 276, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(nombreEstado)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cuidados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Estado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed

    }//GEN-LAST:event_EstadoActionPerformed
  public  void imagenPokemon(int pos){
      if (pos == 0){ Icon icon=new ImageIcon("src/main/java/img/1.png"); imagenPokemon.setIcon(icon);}
      if (pos == 1){ Icon icon=new ImageIcon("src/main/java/img/2.png"); imagenPokemon.setIcon(icon);}
      if (pos == 2){ Icon icon=new ImageIcon("src/main/java/img/3.png"); imagenPokemon.setIcon(icon);}
      if (pos == 3){ Icon icon=new ImageIcon("src/main/java/img/4.png"); imagenPokemon.setIcon(icon);}
      if (pos == 4){ Icon icon=new ImageIcon("src/main/java/img/5.png"); imagenPokemon.setIcon(icon);}
      if (pos == 5){ Icon icon=new ImageIcon("src/main/java/img/6.png"); imagenPokemon.setIcon(icon);}
      if (pos == 6){ Icon icon=new ImageIcon("src/main/java/img/7.png"); imagenPokemon.setIcon(icon);}
      if (pos == 7){ Icon icon=new ImageIcon("src/main/java/img/8.png"); imagenPokemon.setIcon(icon);}
      if (pos == 8){ Icon icon=new ImageIcon("src/main/java/img/9.png"); imagenPokemon.setIcon(icon);}
      if (pos == 9){ Icon icon=new ImageIcon("src/main/java/img/10.png"); imagenPokemon.setIcon(icon);}
      if (pos == 10){ Icon icon=new ImageIcon("src/main/java/img/11.png"); imagenPokemon.setIcon(icon);}
      if (pos == 11){ Icon icon=new ImageIcon("src/main/java/img/12.png"); imagenPokemon.setIcon(icon);}
      if (pos == 12){ Icon icon=new ImageIcon("src/main/java/img/13.png"); imagenPokemon.setIcon(icon);}
      if (pos == 13){ Icon icon=new ImageIcon("src/main/java/img/14.png"); imagenPokemon.setIcon(icon);}
      if (pos == 14){ Icon icon=new ImageIcon("src/main/java/img/15.png"); imagenPokemon.setIcon(icon);}
      if (pos == 15){ Icon icon=new ImageIcon("src/main/java/img/16.png"); imagenPokemon.setIcon(icon);}
      if (pos == 16){ Icon icon=new ImageIcon("src/main/java/img/17.png"); imagenPokemon.setIcon(icon);}
      if (pos == 17){ Icon icon=new ImageIcon("src/main/java/img/18.png"); imagenPokemon.setIcon(icon);}
      if (pos == 18){ Icon icon=new ImageIcon("src/main/java/img/19.png"); imagenPokemon.setIcon(icon);}
      if (pos == 19){ Icon icon=new ImageIcon("src/main/java/img/20.png"); imagenPokemon.setIcon(icon);}
      if (pos == 20){ Icon icon=new ImageIcon("src/main/java/img/21.png"); imagenPokemon.setIcon(icon);}
      if (pos == 21){ Icon icon=new ImageIcon("src/main/java/img/22.png"); imagenPokemon.setIcon(icon);}
      if (pos == 22){ Icon icon=new ImageIcon("src/main/java/img/23.png"); imagenPokemon.setIcon(icon);}
      if (pos == 23){ Icon icon=new ImageIcon("src/main/java/img/24.png"); imagenPokemon.setIcon(icon);}
      if (pos == 24){ Icon icon=new ImageIcon("src/main/java/img/25.png"); imagenPokemon.setIcon(icon);}
      if (pos == 25){ Icon icon=new ImageIcon("src/main/java/img/26.png"); imagenPokemon.setIcon(icon);}
      if (pos == 26){ Icon icon=new ImageIcon("src/main/java/img/27.png"); imagenPokemon.setIcon(icon);}
      if (pos == 27){ Icon icon=new ImageIcon("src/main/java/img/28.png"); imagenPokemon.setIcon(icon);}
      if (pos == 28){ Icon icon=new ImageIcon("src/main/java/img/29.png"); imagenPokemon.setIcon(icon);}
      if (pos == 29){ Icon icon=new ImageIcon("src/main/java/img/30.png"); imagenPokemon.setIcon(icon);}
      if (pos == 30){ Icon icon=new ImageIcon("src/main/java/img/31.png"); imagenPokemon.setIcon(icon);}
      if (pos == 31){ Icon icon=new ImageIcon("src/main/java/img/32.png"); imagenPokemon.setIcon(icon);}
      if (pos == 32){ Icon icon=new ImageIcon("src/main/java/img/33.png"); imagenPokemon.setIcon(icon);}
      if (pos == 33){ Icon icon=new ImageIcon("src/main/java/img/34.png"); imagenPokemon.setIcon(icon);}
      if (pos == 34){ Icon icon=new ImageIcon("src/main/java/img/35.png"); imagenPokemon.setIcon(icon);}
      if (pos == 35){ Icon icon=new ImageIcon("src/main/java/img/36.png"); imagenPokemon.setIcon(icon);}
      if (pos == 36){ Icon icon=new ImageIcon("src/main/java/img/37.png"); imagenPokemon.setIcon(icon);}
      if (pos == 37){ Icon icon=new ImageIcon("src/main/java/img/38.png"); imagenPokemon.setIcon(icon);}
      if (pos == 38){ Icon icon=new ImageIcon("src/main/java/img/39.png"); imagenPokemon.setIcon(icon);}
      if (pos == 39){ Icon icon=new ImageIcon("src/main/java/img/40.png"); imagenPokemon.setIcon(icon);}
      if (pos == 40){ Icon icon=new ImageIcon("src/main/java/img/41.png"); imagenPokemon.setIcon(icon);}
      if (pos == 41){ Icon icon=new ImageIcon("src/main/java/img/42.png"); imagenPokemon.setIcon(icon);}
      if (pos == 42){ Icon icon=new ImageIcon("src/main/java/img/43.png"); imagenPokemon.setIcon(icon);}
      if (pos == 43){ Icon icon=new ImageIcon("src/main/java/img/44.png"); imagenPokemon.setIcon(icon);}
      if (pos == 44){ Icon icon=new ImageIcon("src/main/java/img/45.png"); imagenPokemon.setIcon(icon);}
      if (pos == 45){ Icon icon=new ImageIcon("src/main/java/img/46.png"); imagenPokemon.setIcon(icon);}
      if (pos == 46){ Icon icon=new ImageIcon("src/main/java/img/47.png"); imagenPokemon.setIcon(icon);}
      if (pos == 47){ Icon icon=new ImageIcon("src/main/java/img/48.png"); imagenPokemon.setIcon(icon);}
      if (pos == 48){ Icon icon=new ImageIcon("src/main/java/img/49.png"); imagenPokemon.setIcon(icon);}
      if (pos == 49){ Icon icon=new ImageIcon("src/main/java/img/50.png"); imagenPokemon.setIcon(icon);}
      if (pos == 50){ Icon icon=new ImageIcon("src/main/java/img/51.png"); imagenPokemon.setIcon(icon);}
      if (pos == 51){ Icon icon=new ImageIcon("src/main/java/img/52.png"); imagenPokemon.setIcon(icon);}
      if (pos == 52){ Icon icon=new ImageIcon("src/main/java/img/53.png"); imagenPokemon.setIcon(icon);}
      if (pos == 53){ Icon icon=new ImageIcon("src/main/java/img/54.png"); imagenPokemon.setIcon(icon);}
      if (pos == 54){ Icon icon=new ImageIcon("src/main/java/img/55.png"); imagenPokemon.setIcon(icon);}
      if (pos == 55){ Icon icon=new ImageIcon("src/main/java/img/56.png"); imagenPokemon.setIcon(icon);}
      if (pos == 56){ Icon icon=new ImageIcon("src/main/java/img/57.png"); imagenPokemon.setIcon(icon);}
      if (pos == 57){ Icon icon=new ImageIcon("src/main/java/img/58.png"); imagenPokemon.setIcon(icon);}
      if (pos == 58){ Icon icon=new ImageIcon("src/main/java/img/59.png"); imagenPokemon.setIcon(icon);}
      if (pos == 59){ Icon icon=new ImageIcon("src/main/java/img/60.png"); imagenPokemon.setIcon(icon);}
      if (pos == 60){ Icon icon=new ImageIcon("src/main/java/img/61.png"); imagenPokemon.setIcon(icon);}
      if (pos == 61){ Icon icon=new ImageIcon("src/main/java/img/62.png"); imagenPokemon.setIcon(icon);}
      if (pos == 62){ Icon icon=new ImageIcon("src/main/java/img/63.png"); imagenPokemon.setIcon(icon);}
      if (pos == 63){ Icon icon=new ImageIcon("src/main/java/img/64.png"); imagenPokemon.setIcon(icon);}
      if (pos == 64){ Icon icon=new ImageIcon("src/main/java/img/65.png"); imagenPokemon.setIcon(icon);}
      if (pos == 65){ Icon icon=new ImageIcon("src/main/java/img/66.png"); imagenPokemon.setIcon(icon);}
      if (pos == 66){ Icon icon=new ImageIcon("src/main/java/img/67.png"); imagenPokemon.setIcon(icon);}
      if (pos == 67){ Icon icon=new ImageIcon("src/main/java/img/68.png"); imagenPokemon.setIcon(icon);}
      if (pos == 68){ Icon icon=new ImageIcon("src/main/java/img/69.png"); imagenPokemon.setIcon(icon);}
      if (pos == 69){ Icon icon=new ImageIcon("src/main/java/img/70.png"); imagenPokemon.setIcon(icon);}
      if (pos == 70){ Icon icon=new ImageIcon("src/main/java/img/71.png"); imagenPokemon.setIcon(icon);}
      if (pos == 71){ Icon icon=new ImageIcon("src/main/java/img/72.png"); imagenPokemon.setIcon(icon);}
      if (pos == 72){ Icon icon=new ImageIcon("src/main/java/img/73.png"); imagenPokemon.setIcon(icon);}
      if (pos == 73){ Icon icon=new ImageIcon("src/main/java/img/74.png"); imagenPokemon.setIcon(icon);}
      if (pos == 74){ Icon icon=new ImageIcon("src/main/java/img/75.png"); imagenPokemon.setIcon(icon);}
      if (pos == 75){ Icon icon=new ImageIcon("src/main/java/img/76.png"); imagenPokemon.setIcon(icon);}
      if (pos == 76){ Icon icon=new ImageIcon("src/main/java/img/77.png"); imagenPokemon.setIcon(icon);}
      if (pos == 77){ Icon icon=new ImageIcon("src/main/java/img/78.png"); imagenPokemon.setIcon(icon);}
      if (pos == 78){ Icon icon=new ImageIcon("src/main/java/img/79.png"); imagenPokemon.setIcon(icon);}
      if (pos == 79){ Icon icon=new ImageIcon("src/main/java/img/80.png"); imagenPokemon.setIcon(icon);}
      if (pos == 80){ Icon icon=new ImageIcon("src/main/java/img/81.png"); imagenPokemon.setIcon(icon);}
      if (pos == 81){ Icon icon=new ImageIcon("src/main/java/img/82.png"); imagenPokemon.setIcon(icon);}
      if (pos == 82){ Icon icon=new ImageIcon("src/main/java/img/83.png"); imagenPokemon.setIcon(icon);}
      if (pos == 83){ Icon icon=new ImageIcon("src/main/java/img/84.png"); imagenPokemon.setIcon(icon);}
      if (pos == 84){ Icon icon=new ImageIcon("src/main/java/img/85.png"); imagenPokemon.setIcon(icon);}
      if (pos == 85){ Icon icon=new ImageIcon("src/main/java/img/86.png"); imagenPokemon.setIcon(icon);}
      if (pos == 86){ Icon icon=new ImageIcon("src/main/java/img/87.png"); imagenPokemon.setIcon(icon);}
      if (pos == 87){ Icon icon=new ImageIcon("src/main/java/img/88.png"); imagenPokemon.setIcon(icon);}
      if (pos == 88){ Icon icon=new ImageIcon("src/main/java/img/89.png"); imagenPokemon.setIcon(icon);}
      if (pos == 89){ Icon icon=new ImageIcon("src/main/java/img/90.png"); imagenPokemon.setIcon(icon);}
      if (pos == 90){ Icon icon=new ImageIcon("src/main/java/img/91.png"); imagenPokemon.setIcon(icon);}
      if (pos == 91){ Icon icon=new ImageIcon("src/main/java/img/92.png"); imagenPokemon.setIcon(icon);}
      if (pos == 92){ Icon icon=new ImageIcon("src/main/java/img/93.png"); imagenPokemon.setIcon(icon);}
      if (pos == 93){ Icon icon=new ImageIcon("src/main/java/img/94.png"); imagenPokemon.setIcon(icon);}
      if (pos == 94){ Icon icon=new ImageIcon("src/main/java/img/95.png"); imagenPokemon.setIcon(icon);}
      if (pos == 95){ Icon icon=new ImageIcon("src/main/java/img/96.png"); imagenPokemon.setIcon(icon);}
      if (pos == 96){ Icon icon=new ImageIcon("src/main/java/img/97.png"); imagenPokemon.setIcon(icon);}
      if (pos == 97){ Icon icon=new ImageIcon("src/main/java/img/98.png"); imagenPokemon.setIcon(icon);}
      if (pos == 98){ Icon icon=new ImageIcon("src/main/java/img/99.png"); imagenPokemon.setIcon(icon);}
      if (pos == 99){ Icon icon=new ImageIcon("src/main/java/img/100.png"); imagenPokemon.setIcon(icon);}
//THIS
      if (pos == 100){ Icon icon=new ImageIcon("src/main/java/img/101.png"); imagenPokemon.setIcon(icon);}
      if (pos == 101){ Icon icon=new ImageIcon("src/main/java/img/102.png"); imagenPokemon.setIcon(icon);}
      if (pos == 102){ Icon icon=new ImageIcon("src/main/java/img/103.png"); imagenPokemon.setIcon(icon);}
      if (pos == 103){ Icon icon=new ImageIcon("src/main/java/img/104.png"); imagenPokemon.setIcon(icon);}
      if (pos == 104){ Icon icon=new ImageIcon("src/main/java/img/105.png"); imagenPokemon.setIcon(icon);}
      if (pos == 105){ Icon icon=new ImageIcon("src/main/java/img/106.png"); imagenPokemon.setIcon(icon);}
      if (pos == 106){ Icon icon=new ImageIcon("src/main/java/img/107.png"); imagenPokemon.setIcon(icon);}
      if (pos == 107){ Icon icon=new ImageIcon("src/main/java/img/108.png"); imagenPokemon.setIcon(icon);}
      if (pos == 108){ Icon icon=new ImageIcon("src/main/java/img/109.png"); imagenPokemon.setIcon(icon);}
      if (pos == 109){ Icon icon=new ImageIcon("src/main/java/img/110.png"); imagenPokemon.setIcon(icon);}
      if (pos == 110){ Icon icon=new ImageIcon("src/main/java/img/111.png"); imagenPokemon.setIcon(icon);}
      if (pos == 111){ Icon icon=new ImageIcon("src/main/java/img/112.png"); imagenPokemon.setIcon(icon);}
      if (pos == 112){ Icon icon=new ImageIcon("src/main/java/img/113.png"); imagenPokemon.setIcon(icon);}
      if (pos == 113){ Icon icon=new ImageIcon("src/main/java/img/114.png"); imagenPokemon.setIcon(icon);}
      if (pos == 114){ Icon icon=new ImageIcon("src/main/java/img/115.png"); imagenPokemon.setIcon(icon);}
      if (pos == 115){ Icon icon=new ImageIcon("src/main/java/img/116.png"); imagenPokemon.setIcon(icon);}
      if (pos == 116){ Icon icon=new ImageIcon("src/main/java/img/117.png"); imagenPokemon.setIcon(icon);}
      if (pos == 117){ Icon icon=new ImageIcon("src/main/java/img/118.png"); imagenPokemon.setIcon(icon);}
      if (pos == 118){ Icon icon=new ImageIcon("src/main/java/img/119.png"); imagenPokemon.setIcon(icon);}
      if (pos == 119){ Icon icon=new ImageIcon("src/main/java/img/120.png"); imagenPokemon.setIcon(icon);}
      if (pos == 120){ Icon icon=new ImageIcon("src/main/java/img/121.png"); imagenPokemon.setIcon(icon);}
      if (pos == 121){ Icon icon=new ImageIcon("src/main/java/img/122.png"); imagenPokemon.setIcon(icon);}
      if (pos == 122){ Icon icon=new ImageIcon("src/main/java/img/123.png"); imagenPokemon.setIcon(icon);}
      if (pos == 123){ Icon icon=new ImageIcon("src/main/java/img/124.png"); imagenPokemon.setIcon(icon);}
      if (pos == 124){ Icon icon=new ImageIcon("src/main/java/img/125.png"); imagenPokemon.setIcon(icon);}
      if (pos == 125){ Icon icon=new ImageIcon("src/main/java/img/126.png"); imagenPokemon.setIcon(icon);}
      if (pos == 126){ Icon icon=new ImageIcon("src/main/java/img/127.png"); imagenPokemon.setIcon(icon);}
      if (pos == 127){ Icon icon=new ImageIcon("src/main/java/img/128.png"); imagenPokemon.setIcon(icon);}
      if (pos == 128){ Icon icon=new ImageIcon("src/main/java/img/129.png"); imagenPokemon.setIcon(icon);}
      if (pos == 129){ Icon icon=new ImageIcon("src/main/java/img/130.png"); imagenPokemon.setIcon(icon);}
      if (pos == 130){ Icon icon=new ImageIcon("src/main/java/img/131.png"); imagenPokemon.setIcon(icon);}
      if (pos == 131){ Icon icon=new ImageIcon("src/main/java/img/132.png"); imagenPokemon.setIcon(icon);}
      if (pos == 132){ Icon icon=new ImageIcon("src/main/java/img/133.png"); imagenPokemon.setIcon(icon);}
      if (pos == 133){ Icon icon=new ImageIcon("src/main/java/img/134.png"); imagenPokemon.setIcon(icon);}
      if (pos == 134){ Icon icon=new ImageIcon("src/main/java/img/135.png"); imagenPokemon.setIcon(icon);}
      if (pos == 135){ Icon icon=new ImageIcon("src/main/java/img/136.png"); imagenPokemon.setIcon(icon);}
      if (pos == 136){ Icon icon=new ImageIcon("src/main/java/img/137.png"); imagenPokemon.setIcon(icon);}
      if (pos == 137){ Icon icon=new ImageIcon("src/main/java/img/138.png"); imagenPokemon.setIcon(icon);}
      if (pos == 138){ Icon icon=new ImageIcon("src/main/java/img/139.png"); imagenPokemon.setIcon(icon);}
      if (pos == 139){ Icon icon=new ImageIcon("src/main/java/img/140.png"); imagenPokemon.setIcon(icon);}
      if (pos == 140){ Icon icon=new ImageIcon("src/main/java/img/141.png"); imagenPokemon.setIcon(icon);}
      if (pos == 141){ Icon icon=new ImageIcon("src/main/java/img/142.png"); imagenPokemon.setIcon(icon);}
      if (pos == 142){ Icon icon=new ImageIcon("src/main/java/img/143.png"); imagenPokemon.setIcon(icon);}
      if (pos == 143){ Icon icon=new ImageIcon("src/main/java/img/144.png"); imagenPokemon.setIcon(icon);}
      if (pos == 144){ Icon icon=new ImageIcon("src/main/java/img/145.png"); imagenPokemon.setIcon(icon);}
      if (pos == 45){ Icon icon=new ImageIcon("src/main/java/img/146.png"); imagenPokemon.setIcon(icon);}
      if (pos == 146){ Icon icon=new ImageIcon("src/main/java/img/147.png"); imagenPokemon.setIcon(icon);}
      if (pos == 147){ Icon icon=new ImageIcon("src/main/java/img/148.png"); imagenPokemon.setIcon(icon);}
      if (pos == 148){ Icon icon=new ImageIcon("src/main/java/img/149.png"); imagenPokemon.setIcon(icon);}
      if (pos == 149){ Icon icon=new ImageIcon("src/main/java/img/150.png"); imagenPokemon.setIcon(icon);}
      if (pos == 150){ Icon icon=new ImageIcon("src/main/java/img/151.png"); imagenPokemon.setIcon(icon);}
      if (pos == 151){ Icon icon=new ImageIcon("src/main/java/img/152.png"); imagenPokemon.setIcon(icon);}
      if (pos == 152){ Icon icon=new ImageIcon("src/main/java/img/153.png"); imagenPokemon.setIcon(icon);}
      if (pos == 153){ Icon icon=new ImageIcon("src/main/java/img/154.png"); imagenPokemon.setIcon(icon);}
    
    
  }
    private void CuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuidadosActionPerformed
        Llamado una = new Llamado();
        una.llamarCuidados();
        this.setVisible(false);    
    }//GEN-LAST:event_CuidadosActionPerformed

    private void TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiendaActionPerformed
        // TODO add your handling code here:
      Llamado una = new Llamado();
        una.llamarTienda();
        this.setVisible(false);
    }//GEN-LAST:event_TiendaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu m = new Menu();
        Main pokemon = new Main();
        m.PokemonesVivos(pokemon.Pokemones());
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cuidados;
    private javax.swing.JButton Estado;
    private javax.swing.JButton Tienda;
    public javax.swing.JLabel imagenPokemon;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel nombreEstado;
    // End of variables declaration//GEN-END:variables
}
